(self.webpackChunkheart_clear_2204=self.webpackChunkheart_clear_2204||[]).push([[181],{5626:function(e){function i(r,u){(u==null||u>r.length)&&(u=r.length);for(var s=0,n=new Array(u);s<u;s++)n[s]=r[s];return n}e.exports=i,e.exports.__esModule=!0,e.exports.default=e.exports},9329:function(e){function i(r){if(Array.isArray(r))return r}e.exports=i,e.exports.__esModule=!0,e.exports.default=e.exports},9558:function(e){function i(r,u){var s=r==null?null:typeof Symbol<"u"&&r[Symbol.iterator]||r["@@iterator"];if(s!=null){var n=[],t=!0,o=!1,a,c;try{for(s=s.call(r);!(t=(a=s.next()).done)&&(n.push(a.value),!(u&&n.length===u));t=!0);}catch(p){o=!0,c=p}finally{try{!t&&s.return!=null&&s.return()}finally{if(o)throw c}}return n}}e.exports=i,e.exports.__esModule=!0,e.exports.default=e.exports},9548:function(e){function i(){throw new TypeError(`Invalid attempt to destructure non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.`)}e.exports=i,e.exports.__esModule=!0,e.exports.default=e.exports},9875:function(e,i,r){var u=r(9329),s=r(9558),n=r(6562),t=r(9548);function o(a,c){return u(a)||s(a,c)||n(a,c)||t()}e.exports=o,e.exports.__esModule=!0,e.exports.default=e.exports},6562:function(e,i,r){var u=r(5626);function s(n,t){if(!!n){if(typeof n=="string")return u(n,t);var o=Object.prototype.toString.call(n).slice(8,-1);if(o==="Object"&&n.constructor&&(o=n.constructor.name),o==="Map"||o==="Set")return Array.from(n);if(o==="Arguments"||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(o))return u(n,t)}}e.exports=s,e.exports.__esModule=!0,e.exports.default=e.exports},181:function(e,i,r){"use strict";r.r(i),r.d(i,{default:function(){return c}});var u=r(9875),s=r.n(u),n=r(3313),t=r.n(n),o=r(2322),a=function(l){var f=l.src,v=t().useRef(null),d=t().useState(!1),h=s()(d,2),b=h[0],g=h[1];t().useEffect(function(){if(v.current&&!b){var x=document.querySelector(".music-control .tips"),y=x?.classList;y?.contains("showed")===!1&&(y.add("show"),setTimeout(function(){y.remove("show"),y.add("showed")},3e3))}},[b]);var O=function(){if(b){var y;g(!1),(y=v.current)===null||y===void 0||y.pause()}else{var m;g(!0),(m=v.current)===null||m===void 0||m.play()}};return t().useEffect(function(){var x=function(){document.hidden&&(navigator.userAgent.match(/\(i[^;]+;( U;)? CPU.+Mac OS X/)||g(!1))};return document.addEventListener("visibilitychange",x),function(){document.removeEventListener("visibilitychange",x)}},[]),(0,o.jsxs)("button",{id:b?"music_stop":"music_play",className:"music-control",onClick:O,children:[(0,o.jsx)("a",{className:b?"play":"stop",children:(0,o.jsx)("audio",{loop:!0,ref:v,children:(0,o.jsx)("source",{src:f,type:"audio/mpeg"})})}),(0,o.jsx)("div",{className:"tips",children:"\u8FD9\u91CC\u6709\u9996\u5C0F\u97F3\u4E50\u54E6\uFF5E"})]})},c=a},7320:function(e){"use strict";/*
object-assign
(c) Sindre Sorhus
@license MIT
*/var i=Object.getOwnPropertySymbols,r=Object.prototype.hasOwnProperty,u=Object.prototype.propertyIsEnumerable;function s(t){if(t==null)throw new TypeError("Object.assign cannot be called with null or undefined");return Object(t)}function n(){try{if(!Object.assign)return!1;var t=new String("abc");if(t[5]="de",Object.getOwnPropertyNames(t)[0]==="5")return!1;for(var o={},a=0;a<10;a++)o["_"+String.fromCharCode(a)]=a;var c=Object.getOwnPropertyNames(o).map(function(l){return o[l]});if(c.join("")!=="0123456789")return!1;var p={};return"abcdefghijklmnopqrst".split("").forEach(function(l){p[l]=l}),Object.keys(Object.assign({},p)).join("")==="abcdefghijklmnopqrst"}catch{return!1}}e.exports=n()?Object.assign:function(t,o){for(var a,c=s(t),p,l=1;l<arguments.length;l++){a=Object(arguments[l]);for(var f in a)r.call(a,f)&&(c[f]=a[f]);if(i){p=i(a);for(var v=0;v<p.length;v++)u.call(a,p[v])&&(c[p[v]]=a[p[v]])}}return c}},1837:function(e,i,r){"use strict";var u;/** @license React v17.0.2
 * react-jsx-runtime.production.min.js
 *
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */r(7320);var s=r(3313),n=60103;if(u=60107,typeof Symbol=="function"&&Symbol.for){var t=Symbol.for;n=t("react.element"),u=t("react.fragment")}var o=s.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentOwner,a=Object.prototype.hasOwnProperty,c={key:!0,ref:!0,__self:!0,__source:!0};function p(l,f,v){var d,h={},b=null,g=null;v!==void 0&&(b=""+v),f.key!==void 0&&(b=""+f.key),f.ref!==void 0&&(g=f.ref);for(d in f)a.call(f,d)&&!c.hasOwnProperty(d)&&(h[d]=f[d]);if(l&&l.defaultProps)for(d in f=l.defaultProps,f)h[d]===void 0&&(h[d]=f[d]);return{$$typeof:n,type:l,key:b,ref:g,props:h,_owner:o.current}}i.jsx=p,i.jsxs=p},2322:function(e,i,r){"use strict";e.exports=r(1837)}}]);
